/**
* CoEpi Server
* This is the API model for CoEpi Server
*
* OpenAPI spec version: 0.3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package org.coepi.api.models


typealias CenKey = kotlin.String
