/**
* CoEpi Server
* This is the API model for CoEpi Server
*
* OpenAPI spec version: 0.3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package org.coepi.api.models

/**
 * Infection report representing symptoms and/or positive infection incident * @param reportId Unique Identifier of the infection report * @param report Content of the infection report consisting of symptoms and/or positive infection incident. Base64 encoded * @param cenKeys CEN Keys belonging to the device that publushed the report * @param reportTimestamp */
data class Report (    /* Unique Identifier of the infection report */
        var reportId: kotlin.String? = null,    /* Content of the infection report consisting of symptoms and/or positive infection incident. Base64 encoded */
        var report: ByteArray? = null,    /* CEN Keys belonging to the device that publushed the report */
        var cenKeys: kotlin.Array<CenKey>? = null,
        var reportTimestamp: java.sql.Timestamp? = null
)
